#!/bin/bash
set -e

cd /workspace
git clone https://github.com/alexrutz/atlas-cag
cd /workspace/atlas-cag/data/models
wget --content-disposition "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-UD-Q4_K_XL.gguf?download=true"
wget --content-disposition "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/mmproj-BF16.gguf?download=true"
wget --content-disposition "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/mtp-gemma-4-E4B-it.gguf?download=true"
